/** Mapa estático UF → principais cidades (capital primeiro, resto em ordem alfabética) */
export const BR_LOCATIONS: Record<string, string[]> = {
  AC: ['Rio Branco', 'Cruzeiro do Sul', 'Sena Madureira'],
  AL: ['Maceió', 'Arapiraca', 'Bayeux', 'Marechal Deodoro', 'Palmeira dos Índios', 'Rio Largo'],
  AM: ['Manaus', 'Itacoatiara', 'Manacapuru', 'Parintins', 'Tefé'],
  AP: ['Macapá', 'Santana'],
  BA: [
    'Salvador',
    'Alagoinhas', 'Camaçari', 'Feira de Santana', 'Ilhéus',
    'Itabuna', 'Jequié', 'Juazeiro', 'Lauro de Freitas',
    'Porto Seguro', 'Simões Filho', 'Vitória da Conquista',
  ],
  CE: [
    'Fortaleza',
    'Caucaia', 'Crato', 'Iguatu', 'Itapipoca',
    'Juazeiro do Norte', 'Maracanaú', 'Quixadá', 'Sobral',
  ],
  DF: ['Brasília', 'Ceilândia', 'Plano Piloto', 'Samambaia', 'Taguatinga'],
  ES: [
    'Vitória',
    'Aracruz', 'Cachoeiro de Itapemirim', 'Cariacica',
    'Colatina', 'Guarapari', 'Linhares', 'São Mateus',
    'Serra', 'Vila Velha',
  ],
  GO: [
    'Goiânia',
    'Águas Lindas de Goiás', 'Anápolis', 'Aparecida de Goiânia',
    'Formosa', 'Luziânia', 'Novo Gama', 'Rio Verde',
    'Trindade', 'Valparaíso de Goiás',
  ],
  MA: [
    'São Luís',
    'Açailândia', 'Bacabal', 'Caxias', 'Imperatriz',
    'Paço do Lumiar', 'São José de Ribamar', 'Timon',
  ],
  MG: [
    'Belo Horizonte',
    'Betim', 'Contagem', 'Divinópolis', 'Governador Valadares',
    'Ibirité', 'Ipatinga', 'Juiz de Fora', 'Montes Claros',
    'Poços de Caldas', 'Ribeirão das Neves', 'Santa Luzia',
    'Sete Lagoas', 'Uberaba', 'Uberlândia',
  ],
  MS: ['Campo Grande', 'Corumbá', 'Dourados', 'Ponta Porã', 'Três Lagoas'],
  MT: ['Cuiabá', 'Rondonópolis', 'Sinop', 'Tangará da Serra', 'Várzea Grande'],
  PA: [
    'Belém',
    'Abaetetuba', 'Altamira', 'Ananindeua', 'Castanhal',
    'Marabá', 'Parauapebas', 'Santarém',
  ],
  PB: ['João Pessoa', 'Bayeux', 'Campina Grande', 'Patos', 'Santa Rita'],
  PE: [
    'Recife',
    'Cabo de Santo Agostinho', 'Camaragibe', 'Caruaru',
    'Garanhuns', 'Jaboatão dos Guararapes', 'Olinda',
    'Paulista', 'Petrolina',
  ],
  PI: ['Teresina', 'Campo Maior', 'Floriano', 'Parnaíba', 'Picos'],
  PR: [
    'Curitiba',
    'Almirante Tamandaré', 'Araucária', 'Cascavel',
    'Colombo', 'Foz do Iguaçu', 'Guarapuava',
    'Londrina', 'Maringá', 'Paranaguá',
    'Ponta Grossa', 'Umuarama',
  ],
  RJ: [
    'Rio de Janeiro',
    'Angra dos Reis', 'Belford Roxo', 'Cabo Frio',
    'Campos dos Goytacazes', 'Duque de Caxias', 'Macaé',
    'Magé', 'Niterói', 'Nova Iguaçu',
    'Petrópolis', 'Resende', 'São Gonçalo',
    'Teresópolis', 'Volta Redonda',
  ],
  RN: ['Natal', 'Assú', 'Caicó', 'Mossoró', 'Parnamirim'],
  RO: ['Porto Velho', 'Ariquemes', 'Ji-Paraná'],
  RR: ['Boa Vista', 'Rorainópolis'],
  RS: [
    'Porto Alegre',
    'Alvorada', 'Canoas', 'Caxias do Sul',
    'Gravataí', 'Novo Hamburgo', 'Passo Fundo',
    'Pelotas', 'Rio Grande', 'Santa Maria',
    'São Leopoldo', 'Viamão',
  ],
  SC: [
    'Florianópolis',
    'Balneário Camboriú', 'Blumenau', 'Brusque',
    'Chapecó', 'Criciúma', 'Itajaí',
    'Jaraguá do Sul', 'Joinville', 'Palhoça',
    'São José', 'Tubarão',
  ],
  SE: ['Aracaju', 'Itabaiana', 'Lagarto', 'Nossa Senhora do Socorro', 'São Cristóvão'],
  SP: [
    'São Paulo',
    'Bauru', 'Campinas', 'Carapicuíba', 'Franca',
    'Guarulhos', 'Jundiaí', 'Limeira', 'Mauá',
    'Mogi das Cruzes', 'Osasco', 'Piracicaba',
    'Praia Grande', 'Ribeirão Preto', 'Santo André',
    'Santos', 'São Bernardo do Campo', 'São José dos Campos',
    'Sorocaba', 'Taubaté',
  ],
  TO: ['Palmas', 'Araguaína', 'Gurupi'],
}

export const BRAZIL_STATES = [
  { uf: 'AC', label: 'Acre' },
  { uf: 'AL', label: 'Alagoas' },
  { uf: 'AM', label: 'Amazonas' },
  { uf: 'AP', label: 'Amapá' },
  { uf: 'BA', label: 'Bahia' },
  { uf: 'CE', label: 'Ceará' },
  { uf: 'DF', label: 'Distrito Federal' },
  { uf: 'ES', label: 'Espírito Santo' },
  { uf: 'GO', label: 'Goiás' },
  { uf: 'MA', label: 'Maranhão' },
  { uf: 'MG', label: 'Minas Gerais' },
  { uf: 'MS', label: 'Mato Grosso do Sul' },
  { uf: 'MT', label: 'Mato Grosso' },
  { uf: 'PA', label: 'Pará' },
  { uf: 'PB', label: 'Paraíba' },
  { uf: 'PE', label: 'Pernambuco' },
  { uf: 'PI', label: 'Piauí' },
  { uf: 'PR', label: 'Paraná' },
  { uf: 'RJ', label: 'Rio de Janeiro' },
  { uf: 'RN', label: 'Rio Grande do Norte' },
  { uf: 'RO', label: 'Rondônia' },
  { uf: 'RR', label: 'Roraima' },
  { uf: 'RS', label: 'Rio Grande do Sul' },
  { uf: 'SC', label: 'Santa Catarina' },
  { uf: 'SE', label: 'Sergipe' },
  { uf: 'SP', label: 'São Paulo' },
  { uf: 'TO', label: 'Tocantins' },
] as const
