export const NICHES: string[] = [
  'Academias',
  'Advogados',
  'Arquitetos',
  'Barbearias',
  'Clínicas médicas',
  'Construtoras',
  'Contabilidade',
  'Consultores',
  'Creches e escolas',
  'Dentistas',
  'Eletricistas',
  'Encanadores',
  'Escolas de idiomas',
  'Farmácias',
  'Fisioterapeutas',
  'Fotógrafos',
  'Hotéis e pousadas',
  'Imobiliárias',
  'Lanchonetes',
  'Marceneiros',
  'Mecânicas',
  'Nutricionistas',
  'Padarias',
  'Personal trainers',
  'Pet shops',
  'Pintores',
  'Pizzarias',
  'Psicólogos',
  'Restaurantes',
  'Salões de beleza',
  'Seguradoras',
  'Veterinários',
]
